### ISSUE TITLE
Not working on lots of news sites?

### ISSUE THREAD

**Issue by dmil** [PaulKinlan/logseq-webpage-title#15]
Thanks for making this great plugin! I was hoping to use it to grab titles from news sites that I plan to read, but I'm realizing it's not always working for news articles, even when a `<title>` tag is present. I'm not totally sure what the issue is or how to debug a LogSeq plugin, but here are a few examples of where I found it doesn't work.

works on: 
- https://fivethirtyeight.com/features/how-my-fitness-tracker-turned-me-against-myself/

doesn't work on: 
- https://www.axios.com/2020/10/01/google-will-spend-1-billion-to-pay-publishers-for-news-showcase
- https://www.washingtonpost.com/national-security/2022/05/11/ukraine-us-intelligence-sharing-war/
- https://awilkinson.medium.com/the-power-of-anti-goals-c38f5f46d23c

Thanks again!

**Comment by PaulKinlan** [comment]
I'll investigate. Thanks for giving some sample links.  One thing I found is that it doesn't work for Twitter because it "requires" JavaScript so it might be something similar.

**Comment by PaulKinlan** [comment]
I just checked.  https://awilkinson.medium.com/the-power-of-anti-goals-c38f5f46d23c is the only one it doesn't work on for me, and that has a `<title>` element of  `<title data-rh="true"`.. I can fix this one pretty easily.

**Comment by PaulKinlan** [comment]
It should be better now. Can you check? (fixed in https://github.com/PaulKinlan/logseq-webpage-title/commit/c02777975735ce0c9d5f8bf1cf1809b0da15152f)

**Comment by piyush-das** [comment]
Hi, tried the latest release but still fails to work for the following link : [https://leetcode.com/problems/n-queens/](https://leetcode.com/problems/n-queens/)

**Comment by PaulKinlan** [comment]
That's because the site uses JavaScript to update the title. This extension right now can't run JS on those pages

**Comment by dmil** [comment]
Worked great on all three of the ones I had initially cited. Thank you!!!
